### ISSUE TITLE
Hello!! Wanna discuss with libevm subway bot owners!!

### ISSUE THREAD

**Issue by GladBenTeams** [libevm/libevm#1]

**Comment by libevm** [comment]
what do you wanna discuss sir

**Comment by GladBenTeams** [comment]
I was got contacted from Fiverr for development on your bot

**Comment by GladBenTeams** [comment]
The man said he wasn't to add the following functions on your sandwich bot:
https://github.com/libevm/subway/tree/master/bot

Uncle bandit attack protection,
Posion token checker/Honeypot checker;
Bloxroute gateway integration;

+ guide on how to install and run it myself

So I was find that the bot belong to your community

**Comment by libevm** [comment]
Well sounds like you hired the wrong guy. Issue closed.
